//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyRentCar.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        public int CAR_ID { get; set; }
        public string CAR_BRAND { get; set; }
        public string CAR_MODEL { get; set; }
        public byte[] CAR_IMG { get; set; }
        public int CAR_PRICE { get; set; }
        public Nullable<short> CAR_SEATS { get; set; }
        public Nullable<bool> CAR_TRANSMISSION { get; set; }
        public string CAR_FUEL { get; set; }
        public Nullable<short> CAR_DOORS { get; set; }
        public bool CAR_AVAILABLE { get; set; }
    }
}
